### ISSUE TITLE
scau校园网提示打开锁文件失败。。

### ISSUE THREAD

**Issue by 34hammer** [vincenttsang/mentohust-macos#4]
不管哪种dhcp方式都是这个提示
![截屏2020-10-30 上午10 48 52](https://user-images.githubusercontent.com/73678690/97654264-81838580-1a9d-11eb-8825-a60350586429.png)

**Comment by vincenttsang** [comment]
你需要用root权限运行mentohust，试一下sudo -s后运行mentohust能否解决？

從我的iPhone傳送

34hammer <notifications@github.com>於2020年10月30日 10:49寫道：

﻿

不管哪种dhcp方式都是这个提示
[截屏2020-10-30 上午10 48 52]<https://user-images.githubusercontent.com/73678690/97654264-81838580-1a9d-11eb-8825-a60350586429.png>

**Comment by 34hammer** [comment]
弄好了 不过又跳到issue的另一个问题 配合着锐捷客户端解决问题 mac终于能有线了

**Comment by vincenttsang** [comment]
账户名要加@有线1x上网

從我的iPhone傳送

34hammer <notifications@github.com>於2020年11月1日 10:44寫道：

﻿

弄好了 不过又跳到issue的另一个问题 配合着锐捷客户端解决问题 mac终于能有线了

**Comment by 34hammer** [comment]
ok 终于摆脱锐捷了
